# Generated by Django 3.0.4 on 2020-04-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'analyst'), (2, 'developer'), (3, 'admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='tankuser',
            name='roles',
            field=models.ManyToManyField(to='access.Role'),
        ),
    ]
