# Generated by Django 3.1.2 on 2020-11-04 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20200403_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='Europe/Paris', max_length=100)),
            ],
        ),
        migrations.AlterModelManagers(
            name='tankuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='tankuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='tankuser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='tankuser',
            name='settings',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='access.settings'),
            preserve_default=False,
        ),
    ]
