// Error
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
// Me
export const ME_LOADED = 'ME_LOADED';
export const ME_LOAD_FAIL = 'ME_LOAD_FAIL';
export const ME_LOADING = 'ME_LOADING';
export const SETTINGS_UPDATED = 'SETTINGS_UPDATED';
export const SETTINGS_UPDATING = 'SETTINGS_UPDATING';
export const SETTINGS_UPDATE_FAIL = 'SETTINGS_UPDATE_FAIL';
// Runbook
export const ALL_RUNBOOKS_LOADED = 'ALL_RUNBOOKS_LOADED'
export const ALL_RUNBOOKS_LOADING = 'ALL_RUNBOOKS_LOADING'
export const ALL_RUNBOOKS_LOAD_FAIL = 'ALL_RUNBOOKS_LOAD_FAIL'
export const SINGLE_RUNBOOK_LOADED = 'SINGLE_RUNBOOK_LOADED'
export const SINGLE_RUNBOOK_LOADING = 'SINGLE_RUNBOOK_LOADING'
export const SINGLE_RUNBOOK_LOAD_FAIL = 'SINGLE_RUNBOOK_LOAD_FAIL'
export const SINGLE_RUNBOOK_UPDATING = 'SINGLE_RUNBOOK_UPDATING'
export const SINGLE_RUNBOOK_UPDATED = 'SINGLE_RUNBOOK_UPDATED'
export const SINGLE_RUNBOOK_UPDATE_FAILED = 'SINGLE_RUNBOOK_UPDATE_FAILED'
// Users
export const ALL_USERS_LOADED = 'ALL_USERS_LOADED'
export const ALL_USERS_LOADING = 'ALL_USERS_LOADING'
export const ALL_USERS_LOAD_FAIL = 'ALL_USERS_LOAD_FAIL'