# Generated by Django 3.1.2 on 2020-11-04 09:16

from django.db import migrations, models
import runbook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, validators=[runbook.models.RunbookNameValidator()])),
                ('content', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('js', 'JavaScript'), ('sh', 'Shell')], default='python', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
