# Generated by Django 3.1.3 on 2020-11-13 17:40

from django.db import migrations, models
import django.db.models.deletion
import runbook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('running', 'Running'), ('finished', 'Finished'), ('error', 'Error')], default='ready', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, validators=[runbook.models.RunbookNameValidator()])),
                ('content', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('js', 'JavaScript'), ('sh', 'Shell')], default='python', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(default=runbook.models.Worker.get_new, on_delete=django.db.models.deletion.CASCADE, to='runbook.worker')),
            ],
        ),
    ]
