# Generated by Django 3.1.3 on 2020-11-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('status', models.TextField(default=False)),
                ('runbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runbook.runbook')),
            ],
        ),
    ]
